version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: my-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  c2-app:
    image: akash1dev2/c2:latest
    container_name: c2-app
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/testdb

volumes:
  mongo_data:
